version: 2.1
orbs:
  cypress: cypress-io/cypress@2.2.0
workflows:
  build:
    jobs:
      - cypress/run:
          start: 'npm start' # start server before running tests
          wait-on: 'http://localhost:3000'
