version: 2.1
jobs:
  deploy-heroku:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git
orbs:
  cypress: cypress-io/cypress@2.2.0
  heroku: circleci/heroku@1.2.6
workflows:
    build:
      jobs:
        - cypress/install:
            build: "npm run build"
        - cypress/run:
            group: 'all tests' # name this group "all tests" on the dashboard
            start: 'npm start' # start server before running tests
            wait-on: 'http://localhost:3000'
            record: true # records results to the cypress dashboard
            parallel: true
            parallelism: 10 # runs tests in parallel for efficiency
        - deploy-heroku:
            requires:
              - cypress/run
            filters:
              branches:
                only:
                - main