version: 2.1
orbs:
   node: circleci/node@5.1.0
   cypress: cypress-io/cypress@2.2.0
   heroku: circleci/heroku@1.2.6

jobs:
  build:
    docker:
      - image: circleci/node:14.15.1
    steps:
      - checkout
      - run:
          command: npm ci
      - run:
          name: Run build
          command: npm run build
  deploy-heroku:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git

workflows:
  build-test-deploy:
    jobs:
      - build
      - cypress/run:
          requires:
            - build
          group: all tests
          start: npm start
          wait-on: "http://localhost:3000"
          record: true
          parallel: true
          parallelism: 10
      - deploy-heroku:
          requires:
            - build
            - cypress/run
          filters:
            branches:
              only:
                - main