version: 2.1
orbs:
  cypress: cypress-io/cypress@2.2.0
workflows:
  build:
    jobs:
      - cypress/run:
        group: 'all tests'
        start: 'npm start'
        wait-on: 'http://localhost:3000'